name: "Deploy Dir to Static Data"
description: "将当前的一个目录复制到kne-union/static-data仓库的对应目录"
inputs:
  token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: false
  publish_dir:
    description: 'Set an output directory for deployment.'
    required: false
    default: ./build
  name:
    description: 'Set a part name.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'kne-union/static-data'
        ref: 'master'
        token: ${{ inputs.token }}
        path: ./checkout-dir
    - run: cp -r ${{inputs.publish_dir}} ./checkout-dir
      shell: bash
    - run: |
        cd ./checkout-dir
        rm -rf ./${{inputs.name}} && mkdir ./${{inputs.name}}
        cp -r ${{inputs.publish_dir}}/* ./${{inputs.name}}
        rm -rf ${{inputs.publish_dir}}
      shell: bash
    - uses: actions-js/push@master
      with:
        branch: 'master'
        directory: ./checkout-dir
        github_token: ${{ inputs.token }}
